server:
    port: 7001

eureka:
    client:
        service-url:
            defaultZone: http://127.0.0.1:6868/eureka/
    instance:
        prefer-ip-address: true

spring:
    application:
        name: sysgateway
#    redis:
#        host: 127.0.0.1
#        port: 6379
#        password: 123456
    cloud:
        gateway:
            globalcors:
                cors‐configurations:
                    '[/**]': # 匹配所有请求
                        allowedOrigins: "*" #跨域处理 允许所有的域
                        allowedMethods: # 支持的方法
                            - GET
                            - POST
                            - PUT
                            - DELETE
            routes:
#                - id: goods/aa # <网关微服务地址>/<id>/<Path> =(映射)=> <uri>/<Path>
                - id: cg_goods
                  uri: http://127.0.0.1:9011 # 被路由的微服务地址
                  predicates:
                    - Path=/cg_goods/** # 被路由的请求路径，/** 表示所有请求被路由
                  filters:
#                    - StripPrefix=2 # 等于上面id用/分割后的个数
                    - StripPrefix=1
#                    限流配置如下(使用redis的RateLimiter限流算法):
#                    - name: RequestRateLimiter # 请求数限流，名字不能随便写
#                      args:
#                          key-resolver: "#{@ipKeyResolver}"
#                          redis-rate-limiter.replenishRate: 1 # 令牌桶每秒填充数
#                          redis-rate-limiter.burstCapacity: 1 # 令牌桶总容量
                - id: cg_system
                  uri: http://127.0.0.1:9001
                  predicates:
                    - Path=/cg_system/**
                  filters:
                    - StripPrefix=1
